### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by stefnotch** [roseman/idle#3]
Is this project still being maintained? (I'm assuming yes.) 
If I want to add new features to IDLE, which may or may not make it to the official repository, should I contribute here?

One feature that I want to add is: `Shift + Tab` to unindent

**Comment by roseman** [comment]
This was more a private playground. You'll want to go through the official route (bugs.python.org) for that

**Comment by stefnotch** [comment]
Ok! Thanks!
